openapi: 3.1.0
info:
  version: 0.0.0
  title: Power Play API
  description: Developer documentation for the PowerPlay app
  license:
    name: MIT
    url: https://opensource.org/license/mit

paths:
  /auth:
    $ref: "./auth/auth.yml#/paths/auth"
  /chat/channels/create:
    $ref: "./chat/channels.yml#/paths/createChannel"
  /chat/channels/delete:
    $ref: "./chat/channels.yml#/paths/deleteChannel"
  /chat/channels/adduser:
    $ref: "./chat/channels.yml#/paths/addUser"
  /chat/channels/removeuser:
    $ref: "./chat/channels.yml#/paths/removeUser"
  /chat/channels/updateimage:
    $ref: "./chat/channels.yml#/paths/updateChannelImage"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
