openapi: 3.1.0
info:
  version: 0.0.0
  title: Power Play API
  description: Developer documentation for the PowerPlay app
  license:
    name: MIT
    url: https://opensource.org/license/mit

paths:
  /auth:
    $ref: "./auth/auth.yml#/paths/auth"
  /message:
    $ref: "./chat/message.yml#/paths/message"
  /chat/conversations:
    $ref: "./chat/conversations.yml#/paths/listConversations"
  /chat/conversations/create:
    $ref: "./chat/conversations.yml#/paths/createConversation"
  /chat/conversations/delete:
    $ref: "./chat/conversations.yml#/paths/deleteConversation"
  /chat/conversations/adduser:
    $ref: "./chat/conversations.yml#/paths/addUser"
  /chat/conversations/removeuser:
    $ref: "./chat/conversations.yml#/paths/removeUser"
  /chat/conversations/updateimage:
    $ref: "./chat/conversations.yml#/paths/updateConversationImage"
  /chat/conversations/updatedescription:
    $ref: "./chat/conversations.yml#/paths/updateConversationDescription"
  /chat/conversations/rename:
    $ref: "./chat/conversations.yml#/paths/rename"
  /shotsongoal:
    $ref: "./stats/shotsongoal.yml#/paths/shotsOnGoal"
  /penaltyTypes:
    $ref: "./stats/penalties.yml#/paths/penaltyTypes"
  /leagues:
    $ref: "./leagues/leagues.yaml#/paths/leagues"
  /penalties:
    $ref: "./stats/penalties.yml#/paths/penalties"
  /user:
    $ref: "./users/users.yml#/paths/user"

  # /[URL path]
  #$ref: "./[Relative path starting from v1]#/paths/[yml path]"
  /goals:
    $ref: "./stats/goal.yml#/paths/goals"
  /seasons:
    $ref: "./season/season.yml#/paths/seasons"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
